Length Branch for SimiliarityChecker
joo0-hong/Similarity pull request #1
Opened 2024-07-03 23:40 UTC by joo0-hong

Added checking length feature for SimilarityChecker class

2024-07-03 23:51 UTC, jun6ak requested changes

2024-07-03 23:51 UTC, jun6ak commented on Project11/Similarity.cpp
> +			|| a.length() >= b.length() * 2);
`GetScore()`에서와 마찬가지로 더 긴 길이를 찾는 로직이 동일하게 필요하니 함수 호출 전에 실행되거나 함수화 되어도 좋을것같습니다!

2024-07-04 00:06 UTC, joo0-hong commented on Project11/Similarity.cpp
> +			|| a.length() >= b.length() * 2);
리뷰주신 것 처럼 length를 처음부터 사용하니 코드가 훨씬 간결해졌습니다! 코드 수정했습니다 :)

2024-07-04 00:11 UTC, hy-ra-na requested changes

2024-07-04 00:11 UTC, hy-ra-na commented on Project11/Similarity.cpp
> +		if (longlen == shortlen) { return MAX_SCORE; }
줄바꿈 해주시면 어떨까요?

2024-07-04 00:14 UTC, jun6ak approved these changes

2024-07-04 00:14 UTC, joo0-hong commented on Project11/Similarity.cpp
> +		if (longlen == shortlen) { return MAX_SCORE; }
넵! 줄바꿈해서 더 보기 쉽게 수정했습니다 :)

2024-07-04 00:17 UTC, merged